### ISSUE TITLE
CSV files

### ISSUE THREAD

**Issue by Amshaker** [MoMarky/radiology-report-analysis#1]
Hi,

Thank you for sharing your interesting work.

Could you please share the csv files you used in main.py? 

Please at least share openi_findings_label.csv or let me know how you construct it.

Thank you,
Abdelrahman.

**Comment by Amshaker** [comment]
It will be great if you shared the report sections after the pre-precossing.

**Comment by MoMarky** [comment]
> It will be great if you shared the report sections after the pre-precossing.

Hi, thank for you interst of our work. 

I've upload the data after pre-processing. Please find them at '/Results/'.

And i also updated the extraction code for mimic and openI data.  Resource files can be found at '/res/'.

Hope this can help you.

**Comment by Amshaker** [comment]
Thank you so much for providing the files, they are really helpful!
